import json
import os
from pathlib import Path

class SettingsManager:
    def __init__(self):
        self.settings = None
        self.app_data = Path(os.getenv('APPDATA')) / 'Autocorrect'
        self.app_data.mkdir(exist_ok=True)
        self.settings_file = self.app_data / 'settings.json'
        self.load_settings()

    def load_settings(self):
        if self.settings_file.exists():
            with open(self.settings_file, 'r') as f:
                self.settings = json.load(f)
        else:
            self.reset_settings()

    def save_settings(self):
        with open(self.settings_file, 'w') as f:
            json.dump(self.settings, f, indent=4)

    def get_setting(self, key, default=None):
        return self.settings.get(key, default)

    def set_setting(self, key, value):
        self.settings[key] = value
        self.save_settings()

    def get_replacements(self):
        return self.settings.get('replacements', {})

    def reset_settings(self):
        self.settings = {
            'fix.capitalization': True,
            'fix.punctuate': False,
            'fix.german_noun_capitalization': True,
            'fix.use_replacements': True,
            'fix.hotkey': 'Ctrl+F8',
            'fix.auto_fix_on_send': True,
            'rephrase.hotkey': 'Ctrl+F9',
            'rephrase.switch_phrasings_hotkey': 'Ctrl+F10',
            'rephrase.use_replacements': True,
            'rephrase.prompt': 'You are a helpful writing assistant. Provide 3 different concise rephrasing of '
                             'the given text, separated by | characters. Please provide 3 alternative '
                             'phrasings for the following text (The first one just spelling and punctuation '
                             'fixes no different words, only the next phrases should contain alternative words) '
                             '(if the text is longer than 20 words only one alternative phrasing):',

            'translate.hotkey': 'Ctrl+F11',
            'translate.use_replacements': True,
            'translate.alternative_language': 'german',
            'translate.prompt': 'You are a basic translater. Add punctuation and use correct spelling. '
                              'Translate the following text to English if it is in any other language than '
                              'English, else translate it to %alternative_language% and ONLY answer with the '
                              'translated message:',

            'custom_prompt.hotkey': 'Ctrl+F12',
            'custom_prompt.use_replacements': True,
            'custom_prompt.auto_custom_prompt': True,
            'custom_prompt.auto_select_text': True,
            'open_router_key': '',
            'replacements': {
                'i': 'I',
                'jz': 'jetzt',
                'ig': 'I guess',
                'u': 'you',
                'ur': 'your',
                'r': 'are',
                'b4': 'before',
                'btw': 'by the way',
                'tbh': 'to be honest',
                'idc': 'I don’t care',
                'idk': 'I have no idea',
                'imho': 'in my humble opinion',
                'np': 'no problem',
                'nvm': 'never mind',
                'omg': 'oh my god',
                'pls': 'please',
                'tho': 'though',
                'thx': 'thanks',
                'ty': 'thank you',
                'wanna': 'want to',
                'gonna': 'going to',
                'gotta': 'got to',
                'k': 'okay',
                'ok': 'okay',
                'alr': 'alright',
                'lmk': 'let me know',
                'bc': 'because',
                'atm': 'at the moment',
                'ppl': 'people',
                'asap': 'as soon as possible',
                'brb': 'be right back',
                'ftw': 'for the win',
                'imo': 'in my opinion',
                'irl': 'in real life',
                'jk': 'just kidding',
                'fyi': 'for your information',
                'omw': 'on my way',
                'sry': 'sorry',
                'ily': 'I love you',
                'wyd': 'what are you doing',
                'ttyl': 'talk to you later',
                'fr': 'for real',
                'hbu': 'how about you',
                'rn': 'right now',
                'afaik': 'as far as I know',
                'smth': 'something',
                'bcuz': 'because',
                'cuz': 'because',
                'ttys': 'talk to you soon',
                'sup': 'what’s up',
                'imma': 'I am going to',
                'ofc': 'of course',
                'rlly': 'really',
                'yt': 'YouTube',
                'tt': 'TikTok',
                'dc': 'Discord',
                'insta': 'Instagram',
                'bb': 'Bye',
                "its": "it is",
                "didnt": "did not",
                "cant": "cannot",
                "dont": "do not",
                "doesnt": "does not",
                "wont": "will not",
                "wouldnt": "would not",
                "shouldnt": "should not",
                "couldnt": "could not",
                "isnt": "is not",
                "arent": "are not",
                "theres": "there is",
                "heres": "here is",
                "whos": "who is",
                "whats": "what is",
                "whens": "when is",
                "wheres": "where is",
                "whyre": "why are",
                "howre": "how are",
                "whyll": "who will",
                "youll": "you will",
                "theyll": "they will",
                "werent": "were not",
                "hasnt": "has not",
                "havent": "have not",
                "hadnt": "had not",
                "mustnt": "must not",
                "oughtnt": "ought not",
                "mightnt": "might not",
                "dunno": "do not know",
                "outta": "out of",
                "lotta": "lot of",
                "sorta": "sort of",
                "kinda": "kind of",
                "lemme": "let me",
                "gimme": "give me",
                "gotcha": "got you",
                "betcha": "bet you",
                "cmon": "come on",
                "dya": "do you",
                "wha": "what do",
                "gday": "good day",
                "ta": "thank you",
                "wassup": "what is up",
                "yknow": "you know",
                "gottit": "got it",
                "g'day": "good day",
                "coulda": "could have",
                "woulda": "would have",
                "shoulda": "should have",
                "d'you": "do you",
                "ain't": "is not",
                "y'all": "you all",
                "y'gotta": "you have got to",
                "tryna": "trying to",
                "em": "them",
                "let's": "let us",
                "here's": "here is",
                "that's": "that is",
                "there'll": "there will",
                "it'll": "it will",
                "they'd": "they would",
                "she'd": "she would",
                "he'd": "he would",
                "it'd": "it would",
                "we'd": "we would",
                "we're": "we are",
                "they're": "they are",
                "who'd": "who would",
                "who'll": "who will",
                "who're": "who are",
                "who's": "who is",
                "we've": "we have",
                "you've": "you have",
                "I'll": "I will",
                "you'd": "you would",
                "I'd": "I would",
                "he's": "he is",
                "she's": "she is",
                "it's": "it is",
                "they've": "they have",
                "might've": "might have",
                "must've": "must have",
                "not've": "not have",
                "that'd": "that would",
                "this'll": "this will",
                "those'll": "those will",
                "these'll": "these will",
                "what'll": "what will",
                "where'd": "where did",
                "why'd": "why did",
                "how'd": "how did",
                "won't": "will not",
                "needn't": "need not",
                "ma'am": "madam",
                "how's": "how is",
                "y'know": "you know",
                "should've": "should have",
                "could've": "could have",
                "he'll": "he will",
                "she'll": "she will",
                "I'd've": "I would have",
                "you'd've": "you would have",
                "they'd've": "they would have",
                "we'd've": "we would have",
                "it'd've": "it would have",
                "there's": "there is",
                "we'll": "we will",
                "they'll": "they will",
                "y'all'd've": "you all would have",
                "can't've": "cannot have",
                "couldn't've": "could not have",
                "mightn't've": "might not have",
                "mustn't've": "must not have",
                "needn't've": "need not have",
                "shan't": "shall not",
                "shan't've": "shall not have",
                "won't've": "will not have",
                "y'ain't": "you are not",
                "y'ain't've": "you are not have",
                "why're": "why are",
                "what're": "what are",
                "there're": "there are",
                "where're": "where are",
                "what've": "what have",
                "where've": "where have",
                "why've": "why have",
                "couldn't": "could not",
                "haven't": "have not",
                "aren't": "are not",
                "wasn't": "was not",
                "weren't": "were not",
                "didn't": "did not",
                "doesn't": "does not",
                "hasn't": "has not",
                "don't": "do not",
                "let's've": "let us have",
                "somebody'd": "somebody would",
                "somebody'll": "somebody will",
                "somebody's": "somebody is",
                "something'd": "something would",
                "something'll": "something will",
                "something's": "something is",
                "sometime's": "sometime is",
                "sometimes've": "sometimes have",
                "someone'd": "someone would",
                "someone'll": "someone will",
                "someone's": "someone is",
                "nobody'd": "nobody would",
                "nobody'll": "nobody will",
                "nobody's": "nobody is",
                "everybody'd": "everybody would",
                "everybody'll": "everybody will",
                "everybody's": "everybody is",
                "everything'd": "everything would",
                "everything'll": "everything will",
                "everything's": "everything is",
                "nothing'd": "nothing would",
                "nothing'll": "nothing will",
                "nothing's": "nothing is",
                "anybody'd": "anybody would",
                "anybody'll": "anybody will",
                "anybody's": "anybody is",
                "anything'd": "anything would",
                "anything'll": "anything will",
                "anything's": "anything is",
                "oughtn't've": "ought not have",
                "hadn't've": "had not have",
                "hadn't": "had not",
                "y'weren't": "you were not",
                "I'dn't": "I had not",
                "there'd": "there would",
                "that'll": "that will",
                "that'd've": "that would have",
                "which'd": "which would",
                "where'd've": "where did have",
                "who'd've": "who would have",
                "you'll've": "you will have",
                "I'll've": "I will have",
                "we'll've": "we will have",
                "they'll've": "they will have",
                "she'll've": "she will have",
                "he'll've": "he will have",
                "it'll've": "it will have",
                "who'll've": "who will have",
                "y'all've": "you all have",
                "y'all're": "you all are",
                "how'll": "how will",
                "how'd've": "how did have",
                "mustn't": "must not",
                "wouldn't've": "would not have",
                "who's'll": "who is will",
                "you's'll": "you is will",
                "o'clock": "of the clock",
                "yessir": "yes sir",
                "yes'm": "yes madam",
                "cause": "because",
                "yk": "you know"
            }
        }
        self.save_settings()